@startuml
skinparam classAttributeIconSize 0

enum ТипПатрона {
    боевой
    холостой
}

enum СтатусСессии {
    зарядка
    раздача предметов
    ход
    конецИгры
}

class ИгроваяСессия {
    - id
    + статус
    + текущий игрок
}

class Игрок {
    - id
    + имя
    + здоровье
    + в наручниках
    + использовать предмет
}

class Дробовик {
    - магазин
    + зарядить
    + выстрелить
    + подсмотреть
}

class Инвентарь {
    + размер
    + добавить предмет
    + удалить предмет
}

class Предмет {
    + название
    + эффект
}

class ИсторияМатча {
    - id
    + победитель
    + проигравшие
}

class Статистика {
    + победы
    + поражения
    + винрейт
}

' Связи (Relationships)
ИгроваяСессия *-- Игрок : управляется
ИгроваяСессия *-- Дробовик : содержит
ИгроваяСессия -- ИсторияМатча : порождает

Игрок *-- Инвентарь : владеет
Инвентарь o-- Предмет : хранит
Игрок -- Статистика : имеет

Дробовик ..> ТипПатрона : использует

@enduml
