@startuml

skinparam classAttributeIconSize 0

' --- Интерфейсы и Абстракции (I) ---

interface GameContext {
    + peekNextAmmo(): AmmoType
    + healActivePlayer(amount: Int)
    + doubleNextDamage()
    + skipNextOpponent()
}

interface Item {
    + name: String
    + applyEffect(context: GameContext, user: Player)
}

' --- Основные классы (C) ---

class AppLauncher {
    - currentSession: GameSession
    + main(args: Array<String>)
    + run()
}

class GameSession implements GameContext{
    - id: UUID
    - status: SessionStatus
    - players: List<Player>
    - shotgun: Shotgun
    - currentPlayerIdx: Int
    
    + nextTurn()
    + shot(target: Player)
    
    + peekNextAmmo(): AmmoType
    + healActivePlayer(amount: Int)
    + doubleNextDamage()
    + skipNextOpponent()
}

class Shotgun {
    - barrel: MutableList<AmmoType>
    + load(live: Int, blank: Int)
    + fire(): AmmoType
    + peek(): AmmoType
    + isEmpty(): Boolean
}

class Player {
    - id: UUID
    + name: String
    - health: Int
    - isCuffed: Boolean
    - isBuffed: Boolean
    - inventory: MutableList<Item>
    
    + takeDamage(value: Int)
    + heal(value: Int)
    + useItem(item: Item, context: GameContext)
}

class Statistics {
    + wins: Int
    + totalGames: Int
    + calculateWinRate(): Double
}

class MatchHistory {
    - matchId: UUID
    + winnerId: UUID
    + losersId: List<UUID>
    + save()
}

' --- Перечисления (E) ---

enum AmmoType {
    LIVE
    BLANK
}

enum SessionStatus {
    LOADING
    DEALING
    PLAYER_TURN
    GAME_OVER
}

' --- Отношения и зависимости ---

AppLauncher "1" *-- "0..1" GameSession
GameSession "1" *-- "2..4" Player
GameSession "1" *-- "1" Shotgun
GameSession "1" *-- "1" SessionStatus

Item ..> GameContext
Player "1" *-- "1" Statistics
Player "1" o-- "0..8" Item

Shotgun ..> AmmoType
AppLauncher ..> MatchHistory

@enduml
